### ISSUE TITLE
[BUG] Cannot find name 'AnchorPositioningPolyfillOptions' in v0.3.0

### ISSUE THREAD

**Issue by Th3S4mur41** [oddbird/css-anchor-positioning#264]
**Describe the bug**
Running `npx -p typescript tsc index.mjs --declaration --allowJs --emitDeclarationOnly` end in the following error:

```bash
node_modules/@oddbird/css-anchor-positioning/dist/polyfill.d.ts(17,72): error TS2304: Cannot find name 'AnchorPositioningPolyfillOptions'.
tsc exited with code 2
```

Running the same command worked fine with v0.2.0

**Additional context**
The `tsconfig.json`

```json
{
	"compilerOptions": {
		"target": "ES2020",
		"experimentalDecorators": true,
		"useDefineForClassFields": false,
		"module": "ESNext",
		"lib": ["ES2020", "DOM", "DOM.Iterable"],
		"skipLibCheck": true,

		/* Bundler mode */
		"moduleResolution": "bundler",
		"allowImportingTsExtensions": true,
		"resolveJsonModule": true,
		"isolatedModules": true,
		"noEmit": true,

		/* Linting */
		"strict": true,
		"noUnusedLocals": true,
		"noUnusedParameters": true,
		"noFallthroughCasesInSwitch": true,

		/* Project */
		"declaration": true,
		"declarationMap": true,
		"sourceMap": true,
		"inlineSources": true,
		"rootDir": "./src",
		"outDir": "./dist/",

		/* Custom */
		"noImplicitReturns": true,
		"noImplicitAny": true,
		"noImplicitThis": true,
		"allowSyntheticDefaultImports": true,
		"forceConsistentCasingInFileNames": true,
		"noImplicitOverride": true,
		"plugins": [
			{
				"name": "ts-lit-plugin",
				"strict": true
			}
		]
	},
	"include": ["src"]
}
```

**Comment by jgerigmeyer** [comment]
@Th3S4mur41 Thanks! Fixed in [v0.3.1](https://github.com/oddbird/css-anchor-positioning/releases/tag/v0.3.1).
